apiVersion: v1
kind: Pod
metadata:
  name: log-tester
  namespace: default
  labels:
    app: log-tester
spec:
  restartPolicy: Never
  containers:
  - name: logger
    image: bash:5.2
    command:
    - bash
    - -lc
    - |
      for i in $(seq 1 5); do
        ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo "{\"ts\":\"$ts\",\"level\":\"info\",\"service\":\"demo\",\"msg\":\"hello $i\"}"
        sleep 1
      done
      echo "{\"ts\":\"$ts\",\"level\":\"error\",\"service\":\"demo\",\"msg\":\"something went wrong\"}"
