apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
imagePullSecrets:
- name: harbor-test-app-cred
spec:
  replicas: 1
  selector:
    matchLabels:
      component: front
  template:
    metadata:
      labels:
        component: front
    spec:
      containers:
      - name: front
        image: cr.larsfriis.dev/test/frontend:latest
        ports:
        - containerPort: 8181
