apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-deployment
imagePullSecrets:
- name: harbor-test-app-cred
spec:
  replicas: 1
  selector:
    matchLabels:
      component: micro
  template:
    metadata:
      labels:
        component: micro
    spec:
      containers:
      - name: micro
        image: cr.larsfriis.dev/test/micro:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP
          value: my-cluster-kafka-bootstrap.kafka:9092
